config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :bulls

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bull.rb
class Bull < ApplicationRecord
  validates :registration_code,:name, :born_on, :offspring_count, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bulls_controller.rb
class BullsController < ApplicationController
  before_action :set_bull, only: %i[ show edit update destroy ]

  # GET /bulls or /bulls.json
  def index
    @bulls = Bull.all
  end

  # GET /bulls/1 or /bulls/1.json
  def show
  end

  # GET /bulls/new
  def new
    @bull = Bull.new
  end

  # GET /bulls/1/edit
  def edit
  end

  # POST /bulls or /bulls.json
  def create
    @bull = Bull.new(bull_params)

    respond_to do |format|
      if @bull.save
        format.html { redirect_to bull_url(@bull), notice: "Bull was successfully created." }
        format.json { render :show, status: :created, location: @bull }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bull.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulls/1 or /bulls/1.json
  def update
    respond_to do |format|
      if @bull.update(bull_params)
        format.html { redirect_to bull_url(@bull), notice: "Bull was successfully updated." }
        format.json { render :show, status: :ok, location: @bull }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bull.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulls/1 or /bulls/1.json
  def destroy
    @bull.destroy!

    respond_to do |format|
      format.html { redirect_to bulls_url, notice: "Bull was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bull
      @bull = Bull.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bull_params
      params.require(:bull).permit(:name, :born_on, :offspring_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulls_helper.rb
module BullsHelper
end

app/views/bulls/_bull.html.erb
<div id="<%= dom_id bull %>">
  <p>
    <strong>Name:</strong>
    <%= bull.name %>
  </p>

  <p>
    <strong>Born on:</strong>
    <%= bull.born_on %>
  </p>

  <p>
    <strong>Offspring count:</strong>
    <%= bull.offspring_count %>
  </p>

</div>

app/views/bulls/_form.html.erb
<%= form_with(model: bull) do |form| %>
  <% if bull.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bull.errors.count, "error") %> prohibited this bull from being saved:</h2>

      <ul>
        <% bull.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :born_on, style: "display: block" %>
    <%= form.date_field :born_on %>
  </div>

  <div>
    <%= form.label :offspring_count, style: "display: block" %>
    <%= form.number_field :offspring_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bulls/edit.html.erb
<h1>Editing bull</h1>

<%= render "form", bull: @bull %>

<br>

<div>
  <%= link_to "Show this bull", @bull %> |
  <%= link_to "Back to bulls", bulls_path %>
</div>

app/views/bulls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bulls</h1>

<div id="bulls">
  <% @bulls.each do |bull| %>
    <%= render bull %>
    <p>
      <%= link_to "Show this bull", bull %>
    </p>
  <% end %>
</div>

<%= link_to "New bull", new_bull_path %>

app/views/bulls/new.html.erb
<h1>New bull</h1>

<%= render "form", bull: @bull %>

<br>

<div>
  <%= link_to "Back to bulls", bulls_path %>
</div>

app/views/bulls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bull %>

<div>
  <%= link_to "Edit this bull", edit_bull_path(@bull) %> |
  <%= link_to "Back to bulls", bulls_path %>

  <%= button_to "Destroy this bull", @bull, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImportBullsWithXlsx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>